// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZ_Oh98qZYR24iztpfVt4xJBWqkLo6jc',
    appId: '1:1082865093851:web:77fbb76b6b3a1bd08990fe',
    messagingSenderId: '1082865093851',
    projectId: 'authtutorial-b2bb6',
    authDomain: 'authtutorial-b2bb6.firebaseapp.com',
    storageBucket: 'authtutorial-b2bb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSnL7w5DQf7jLrQkhZ_eMK_3cyuWNsAE',
    appId: '1:1082865093851:android:cf2bcd5d7069aa838990fe',
    messagingSenderId: '1082865093851',
    projectId: 'authtutorial-b2bb6',
    storageBucket: 'authtutorial-b2bb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1pozYkABZYveDSp4ChPIvmeuZm8eXto',
    appId: '1:1082865093851:ios:0d77eaa6c4b095268990fe',
    messagingSenderId: '1082865093851',
    projectId: 'authtutorial-b2bb6',
    storageBucket: 'authtutorial-b2bb6.appspot.com',
    androidClientId: '1082865093851-gac6br5kh45ffscm7n1ttvk0mntp15st.apps.googleusercontent.com',
    iosClientId: '1082865093851-p6svcvvidghvqdo9s039v69s97n7kouu.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdminpanel',
  );
}
